package com.habitflow;
import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.view.animation.*;import android.widget.*;import java.text.*;import java.util.*;
public class MainActivity extends Activity{
 LinearLayout root,content,nav; android.content.SharedPreferences sp; int purple=Color.rgb(124,92,255); ArrayList<Habit> habits=new ArrayList<>(); int money=0,streak=0,best=0; String fire="#FF6B35"; String[] cs={"#ff595e","#ff7b54","#ff924c","#ffca3a","#a7c957","#6a994e","#2ec4b6","#00b4d8","#48cae4","#4cc9f0","#4895ef","#4361ee","#3a0ca3","#7209b7","#b5179e","#f72585","#e76f51","#f4a261","#e9c46a","#2a9d8f","#264653","#8ac926","#1982c4","#6a4c93","#ff006e","#8338ec","#3a86ff","#fb5607","#ffbe0b","#06d6a0","#118ab2","#073b4c","#ef476f","#ffd166","#06d6a0","#8ecae6","#219ebc","#023047","#ffb703","#fb8500","#cdb4db","#ffc8dd","#ffafcc","#bde0fe","#a2d2ff","#ccd5ae","#e9edc9","#d4a373","#faedcd","#f94144"};
 String[] skins={"Pixel Dawn|12|🟥🟧🟨","Neon Grid|35|🟪🟦⬛","Forest|80|🟩🟫🟩","Ocean|150|🟦🟦⬜","Cyber|300|⬛🟣🟦","Sunset|500|🟥🟧🟪","Royal|750|🟪🟨🟪","Glitch|1000|⬛⬜🟩","Galaxy|1500|🟪⬛🟦","Legend|2000|🟨⬛🟨"};
 int dp(float x){return(int)(x*getResources().getDisplayMetrics().density+.5f);} TextView t(String s,float z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(dp(8),dp(8),dp(8),dp(8));return v;}
 GradientDrawable g(int c,float r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}
 static class Habit{String n,i,c,m;int value,done,st;Habit(String a,String b,String d,String e,int f){n=a;i=b;c=d;m=e;value=f;}}
 public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("hf",0);load();splash();}
 void splash(){FrameLayout f=new FrameLayout(this);f.setBackgroundColor(Color.rgb(8,10,15));TextView x=t("◆",66);x.setTextColor(purple);f.addView(x,new FrameLayout.LayoutParams(dp(100),dp(100),Gravity.CENTER));setContentView(f);x.setScaleX(.2f);x.setScaleY(.2f);x.animate().scaleX(1).scaleY(1).setDuration(650).setInterpolator(new OvershootInterpolator()).withEndAction(()->new Handler().postDelayed(this::build,350)).start();}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(12),dp(16),dp(90));root.setBackgroundColor(Color.rgb(8,10,15));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView b=t("HabitFlow",24);b.setTypeface(null,1);top.addView(b,new LinearLayout.LayoutParams(0,dp(55),1));TextView c=t("💵 "+money+"$",14);c.setGravity(Gravity.CENTER);c.setBackground(g(Color.rgb(30,30,40),20));top.addView(c,new LinearLayout.LayoutParams(dp(105),dp(42)));root.addView(top);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);nav.setBackground(g(Color.rgb(30,30,40),28));String[] n={"⌂\nالرئيسية","✓\nالعادات","🔥\nالستريك","◒\nالإحصائيات","◈\nالمتجر"};for(int i=0;i<n.length;i++){TextView q=t(n[i],11);q.setGravity(Gravity.CENTER);final int k=i;q.setOnClickListener(v->{if(k==0)home();if(k==1)habitPage();if(k==2)streakPage();if(k==3)stats();if(k==4)shop();});nav.addView(q,new LinearLayout.LayoutParams(0,dp(65),1));}root.addView(nav,new LinearLayout.LayoutParams(-1,dp(70)));setContentView(root);home();root.setAlpha(0);root.animate().alpha(1).setDuration(450).start();}
 void clear(){content.removeAllViews();}
 void title(String a,String b){TextView x=t(a,29);x.setTypeface(null,1);content.addView(x);TextView y=t(b,13);y.setTextColor(Color.GRAY);content.addView(y);}
 void card(String a,String b){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(13),dp(16),dp(13));c.setBackground(g(Color.rgb(27,28,38),22));c.addView(t(a,13));TextView v=t(b,27);v.setTypeface(null,1);c.addView(v);content.addView(c,new LinearLayout.LayoutParams(-1,dp(92)));}
 void home(){clear();title("أهلاً بك 👋","تابع عاداتك وابنِ ستريكك يومًا بعد يوم.");card("🔥 الستريك الحالي",streak+" يوم");card("عادات اليوم",doneCount()+" / "+habits.size());card("أفضل ستريك",best+" 🔥");}
 int doneCount(){int x=0;for(Habit h:habits)x+=h.done>0?1:0;return x;}
 void habitPage(){clear();title("العادات","عادات غير محدودة • 50 لون • قياسات متعددة");if(habits.size()==0)content.addView(t("لا توجد عادات بعد. اضغط + لإضافة أول عادة.",15));for(int i=0;i<habits.size();i++){Habit h=habits.get(i);LinearLayout c=new LinearLayout(this);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(10),dp(8),dp(8),dp(8));c.setBackground(g(Color.rgb(27,28,38),20));TextView ic=t(h.i,25);c.addView(ic,new LinearLayout.LayoutParams(dp(50),dp(60)));LinearLayout mid=new LinearLayout(this);mid.setOrientation(LinearLayout.VERTICAL);mid.addView(t(h.n,16));mid.addView(t(h.m+" • "+h.value+"$ • 🔥 "+h.st,12));c.addView(mid,new LinearLayout.LayoutParams(0,dp(60),1));Button ok=new Button(this);ok.setText(h.done>0?"✓":"+");ok.setTextColor(Color.WHITE);ok.setOnClickListener(v->complete(h));c.addView(ok,new LinearLayout.LayoutParams(dp(55),dp(55)));content.addView(c,new LinearLayout.LayoutParams(-1,dp(78)));}Button add=new Button(this);add.setText("＋ إضافة عادة");add.setOnClickListener(v->dialog());content.addView(add,new LinearLayout.LayoutParams(-1,dp(58)));}
 void dialog(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(25,10,25,5);EditText name=new EditText(this);name.setHint("اسم العادة");name.setTextColor(Color.WHITE);l.addView(name);Spinner icon=new Spinner(this);String[] ii={"📚","🏃","💧","🧘","💻","🎯","🎨","🎵","✍️","🌱","⚽","🧠"};icon.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,ii));l.addView(icon);Spinner metric=new Spinner(this);String[] mm={"عدد المرات","الأيام","الوقت"};metric.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,mm));l.addView(metric);EditText val=new EditText(this);val.setHint("قيمة العادة بالدولار");val.setInputType(2);l.addView(val);new AlertDialog.Builder(this).setTitle("إضافة عادة").setView(l).setPositiveButton("إضافة",(d,w)->{int v=0;try{v=Integer.parseInt(val.getText().toString());}catch(Exception e){}habits.add(new Habit(name.getText().toString(),ii[icon.getSelectedItemPosition()],cs[habits.size()%50],mm[metric.getSelectedItemPosition()],v));save();habitPage();}).setNegativeButton("إلغاء",null).show();}
 void complete(Habit h){if(h.done>0)return;h.done=1;h.st++;streak++;best=Math.max(best,streak);money+=h.value;save();habitPage();}
 void streakPage(){clear();title("الستريك 🔥","عد تصاعدي ولون نار قابل للتغيير");card("الستريك الحالي",streak+" يوم");card("أفضل ستريك",best+" يوم");TextView f=t("لون النار",15);content.addView(f);LinearLayout row=new LinearLayout(this);for(int i=0;i<10;i++){Button q=new Button(this);q.setText("🔥");final String col=cs[i];q.setOnClickListener(v->{fire=col;save();});row.addView(q,new LinearLayout.LayoutParams(0,dp(55),1));}content.addView(row);}
 void stats(){clear();title("الإحصائيات","ملخص كل Charts العادات والستريك");card("إجمالي العادات",habits.size()+"");card("إنجازات اليوم",doneCount()+"");card("أفضل ستريك",best+" 🔥");card("الرصيد",money+"$");for(Habit h:habits){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(12),dp(15),dp(12));c.setBackground(g(Color.rgb(27,28,38),20));c.addView(t(h.i+" "+h.n,16));c.addView(t("▁▂▃▅▆▇█  •  "+h.m+"  •  Streak "+h.st,13));content.addView(c,new LinearLayout.LayoutParams(-1,dp(78)));}}
 void shop(){clear();title("المتجر 🛒","10 Pixel Skins • اكسب $ من إنجاز عاداتك");for(int i=0;i<skins.length;i++){String[] s=skins[i].split("\\|");LinearLayout c=new LinearLayout(this);c.setPadding(dp(12),dp(8),dp(8),dp(8));c.setGravity(Gravity.CENTER_VERTICAL);c.setBackground(g(Color.rgb(27,28,38),20));c.addView(t(s[2],28),new LinearLayout.LayoutParams(dp(90),dp(70)));LinearLayout mid=new LinearLayout(this);mid.setOrientation(LinearLayout.VERTICAL);mid.addView(t(s[0],16));mid.addView(t(s[1]+"$",13));c.addView(mid,new LinearLayout.LayoutParams(0,dp(70),1));Button buy=new Button(this);buy.setText("شراء");int price=Integer.parseInt(s[1]);final int ix=i;buy.setOnClickListener(v->{if(money>=price){money-=price;save();shop();}else Toast.makeText(this,"الرصيد غير كافٍ",Toast.LENGTH_SHORT).show();});c.addView(buy,new LinearLayout.LayoutParams(dp(80),dp(55)));content.addView(c,new LinearLayout.LayoutParams(-1,dp(85)));}}
 void save(){sp.edit().putInt("money",money).putInt("streak",streak).putInt("best",best).apply();} void load(){money=sp.getInt("money",0);streak=sp.getInt("streak",0);best=sp.getInt("best",0);}
}